apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring_rest
    labels:
        app: spring_rest
spec :
    replicas : 2
    selector :
        matchLabels :
            app : spring_rest
    template:
        metadata :
            labels:
                app : spring_rest
        spec :
            containers :
            - image : prince2796/spring-docker-kubernetes:alphine.1
              name : spring_rest
              ports :
              - containerPort : 8080
----

apiVersion : v1
kind : service
metadata :
    name : spring_rest
    labels :
        app : spring_rest
spec :
    ports :
      - port : 8080
        protocol : TCP
        targetPort : 8080
    selector :
        app : spring_rest
    type : LoadBalancer        
